### ISSUE TITLE
public方法名不混淆

### ISSUE THREAD

**Issue by lz520520** [jar-analyzer/class-obf#4]
config可以添加一個參數是否混淆public方法，因爲public方法一般會提供給外部類調用，包括一些override的方法是不可以被混淆的

**Comment by 4ra1n** [comment]
感谢建议

override 注解这个 class 里好像是拿不到

不过 public 这个我看看处理下

**Comment by lz520520** [comment]
override确实没有，只能默认下Object的方法名黑名单

**Comment by 4ra1n** [comment]
可以试下 1.3.1 新增以下配置

```yaml
# 一般 public 方法是被外部调用的
# 可以设置该选项为 true 来跳过 public 方法混淆
ignorePublic: false
```
